name: qianduo_midjourney_api
description: A Dart package for interacting with QianDuoDuo's MidJourney API service. Generate, upscale images and monitor task status through MidJourney's API service.
version: 1.0.2
repository: https://github.com/lukefan/midjourney_api_package
homepage: https://github.com/lukefan/midjourney_api_package
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  http: ^1.1.0
  json_annotation: ^4.8.1

dev_dependencies:
  lints: ^2.0.0
  test: ^1.24.0
  build_runner: ^2.4.8
  json_serializable: ^6.7.1

# Additional information about this package
topics:
  - midjourney
  - ai
  - image-generation 